
//Standard libraries
#include <stdio.h>
#include <stdbool.h>
//ESP libraries
#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"
#include "sdkconfig.h" // generated by "make menuconfig"

//Bosch Sensor BME280 librarie
#include "bme280.h"
//Environmetal Chamber libraries
#include "sensor.h"
#include "humidifier.h"
#include "dryer.h"
#include "environmental_chamber_process.h"
#include "environmental_chamber_handlers.h"
#include "environmental_chamber_Control.h"
#include "environmental_chamber_monitor.h"
#include "custom_bool.h"


#define RH_SETPOINT 80
#define TEMP_SETPOINT 1010 //es el "dont care"
#define LOWER_LIM 2
#define UPPER_LIM 2


//void task_environmental_chamber_control();

enviromental_chamber_t test_chamber;

extern QueueHandle_t xQueue_Environmental_Chamber_Monitor;

void app_main(void){

//esto es interno de la funcion Monitor nada mas, es para el test
		enviromental_chamber_monitor_data_t data_2;
		enviromental_chamber_monitor_data_t data;
		data.actualRH=0x33;
		data.actualTemp=0x33;
		data.RH_control_state=CHAMBER_STOPPED;
		data.TEMP_control_state=CHAMBER_STOPPED;

	EnviromentalChamberInit(&test_chamber);

	EnviromentalChamberSetRH(&test_chamber,RH_SETPOINT);

	EnviromentalChamberActivateRH(&test_chamber);


	EnviromentalChamberRun(&test_chamber);


	vTaskDelay(10000/portTICK_PERIOD_MS);

  EnviromentalChamberStop(&test_chamber);


//void CommandMONITORENVIROMENTALCHAMBERHandler(int argc, char **argv){
	//para testear sin el tiny por ahora

			//EnviromentalChamberMonitor(&enviromentalChamberDipCoating);


			Handler_EnviromentalChamberMonitor(&data_2.actualRH,&data_2.actualTemp,&data_2.RH_control_state,&data_2.RH_control_state);
			//agregar la temperatura de target actual !

			if( xQueueSendToBack(xQueue_Environmental_Chamber_Monitor,&data,10) != pdPASS ){
					/* Failed to post the message, even after 10 ticks. */
					printf("Failed to post the message in the xQueue_Environmental_Chamber_Monitor, even after 10 ticks\n");
			}


			if (xQueueReceive( xQueue_Environmental_Chamber_Monitor, &data, portMAX_DELAY) == pdTRUE ){
					 printf("datos a transmitir por socket:\n RH= %f \n state: %d \n",data.actualRH,(int)data.RH_control_state);
					 //transmitir por socket
			}



	vTaskDelay(4000/portTICK_PERIOD_MS);

	EnviromentalChamberSetRH(&test_chamber,RH_SETPOINT+5.1);

	EnviromentalChamberActivateRH(&test_chamber);

	EnviromentalChamberRun(&test_chamber);


}
